name: Leetcode Testing Gitea Actions
run-name: ${{ gitea.actor }} is testing out leetcode problems
on: [push]

jobs:
  Testing Leetcode Problems:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Testing Leetcode Problems
        run: go test -v ./...